import { Button, Divider } from '@mui/material'
import React from 'react'



function Preview({resumeData}) {
  return (
    <div>

      <div className="w-100">
        <h2>{resumeData.fullName || "Full Name"}</h2>
        <p className="fs-6 lh-1">{resumeData.job}</p>
        <p className="fs-6 lh-1">Phone: {resumeData.phone}</p>
        <p className="fs-6 lh-1">Email: {resumeData.email}</p>
        <p className="fs-6 lh-1">LinkedIn: {resumeData.linkedin}</p>
        <p className="fs-6 lh-1">GitHub: {resumeData.github}</p>
        <p className="fs-6 lh-1">Location: {resumeData.location}</p>
        <Divider className = 'bg-dark my-3'/>
        <h4>Professional Summary</h4>
        <p>{resumeData.summary || "Summary will be generated by AI"}</p>
        <Divider className='bg-dark my-3' />
        <h4>Technical Skills</h4>
       <p>skilss here</p>
       {
        resumeData.skills && resumeData.skills.map(skill=>(
          <span><Button key={skill} variant='text' className='text-dark' >{skill}</Button></span>
        ))
       }
        <Divider className='bg-dark my-3'/>
        <h4>Education</h4>
        <p className="fs-6 lh-1">Bachelor's Degree in {resumeData.degree} </p>
        <p className="fs-6 lh-1">College / University Name: {resumeData.college} </p>
        <p className="fs-6 lh-1">Year of Graduation:  {resumeData.year}</p>

      </div>
      
    </div>
  )
}

export default Preview
